/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */
import com.github.rodm.teamcity.DockerTeamCityEnvironment

group = "org.example"
version = "0.1.0"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)
    id("io.github.rodm.teamcity-server")        version "1.5.3"
    id("io.github.rodm.teamcity-environments")  version "1.5.3"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

teamcity {
    version = "2023.03"

    server {
        descriptor {
            name = project.name
            displayName = "Demo Plugin"
            version = project.version as String?
            vendorName = "Nelson Alvarez"
            description = "A demo plugin"
            vendorUrl = "com.example"
            setValidateBeanDefinition("fail")
        }
    }

    environments {

        create("teamcity", DockerTeamCityEnvironment::class.java) {
            version = "2023.11.1"
        }
    }
}

