/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun appExists() {
        assertEquals(10, 10)
    }
}
